applications:
  - '/System/Applications/Mail.app'
  - '/Applications/Google Chrome.app'
  - '/Applications/Slack.app'
  - '/Applications/Telegram Lite.app'
  - '/Applications/WhatsApp.app'
  - '/Applications/Spotify.app'
  - '/System/Applications/Calendar.app'
  - '/Applications/GitHub Desktop.app'
  - '/Applications/Obsidian.app'
  - '/Applications/Ghostty.app'
