repositories:
  - hpedrorodrigues/tools
  - fluxcd/tap
  - homeport/tap

formulas:
  - apktool
  - atuin
  - awscli
  - bash
  - bat
  - bench
  - binutils
  - cloud-sql-proxy
  - coreutils
  - crane
  - dex2jar
  - diffutils
  - dive
  - dockutil
  - dotbot
  - duf
  - ed
  - egctl
  - ffmpeg
  - file-formula
  - findutils
  - fluxcd/tap/flux
  - fzf
  - gawk
  - gcc
  - gettext
  - gh
  - git
  - git-delta
  - git-lfs
  - gnu-indent
  - gnu-sed
  - gnu-tar
  - gnu-which
  - gnupg
  - gnutls
  - go
  - go-task
  - gpatch
  - gradle
  - grep
  - gzip
  - helm
  - hexyl
  - homeport/tap/dyff
  - htmlq
  - htop
  - hugo
  - hwatch
  - hyperfine
  - icdiff
  - ipcalc
  - jadx
  - jless
  - jq
  - kcat
  - kind
  - kotlin
  - krew
  - kubernetes-cli
  - kubespy
  - kustomize
  - leiningen
  - less
  - m4
  - make
  - mas
  - maven
  - mise
  - mtr
  - ncdu
  - nmap
  - openssh
  - pidcat
  - poetry
  - postgresql@17
  - redis
  - rsync
  - sbt
  - scala # Scala 3
  - scala@2.13
  - scrcpy
  - screen
  - shpotify
  - sipcalc
  - sqlite
  - starship
  - stern
  - subnetcalc
  - telnet
  - tmux
  - tree
  - trivy
  - unzip
  - vim
  - wdiff
  - wget
  - yq
  - zoxide
  - zsh-autosuggestions
  - hpedrorodrigues/tools/zsh-defer

casks:
  # - 1password
  - appcleaner
  - bartender
  - claude-code
  - cleanshot
  - clipy
  - codex
  - codexbar
  - deckset
  - discord
  - docker
  - ghostty
  - github
  - google-chrome
  - google-cloud-sdk
  - grammarly-desktop
  - iina
  - istat-menus
  - jetbrains-toolbox
  - keepingyouawake
  - licecap
  - monitorcontrol
  - obsidian
  - postman
  - rectangle
  - spotify
  - tailscale-app
  - temurin@11 # JDK 11
  - temurin@17 # JDK 17
  - temurin@21 # JDK 21
  - vagrant
  - wireshark
  - zed
  - zoom
