repositories:
  - repo: 'https://github.com/VundleVim/Vundle.vim'
    dest: '{{ ansible_facts["user_dir"] }}/.vim/bundle/Vundle.vim'
  - repo: 'https://github.com/jandamm/zgenom.git'
    dest: '{{ ansible_facts["user_dir"] }}/.zgenom'
  - repo: 'https://github.com/tmux-plugins/tpm'
    dest: '{{ ansible_facts["user_dir"] }}/.tmux/plugins/tpm'
